apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-agent
  namespace: investment-agent
spec:
  selector:
    app: sentiment-analysis-agent
  ports:
    - protocol: TCP
      port: 8015
      targetPort: 8015
