apiVersion: v1
kind: Service
metadata:
  name: macro-analysis-agent
  namespace: investment-agent
spec:
  selector:
    app: macro-analysis-agent
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8013
